---
version: '3.7'
services:
  proxy:
    image: nginx:1.14-alpine
    volumes:
      - ./proxy/conf.d/:/etc/nginx/conf.d/
      - ./proxy/logs/:/var/log/nginx/
      - ./proxy/ssl/:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"
    command: ['nginx','-g','daemon off;']
  web1:
    image: nginx:1.14-alpine
    restart: always
    volumes:
      - ./web1/conf.d/:/etc/nginx/conf.d/
      - ./web1/logs/:/var/log/nginx/
      - ./www/:/www/
    expose:
      - "80"
    command: ['nginx','-g','daemon off;']
  web2:
    image: nginx:1.14-alpine
    restart: always
    volumes:
      - ./web2/conf.d/:/etc/nginx/conf.d/
      - ./web2/logs/:/var/log/nginx/
      - ./www/:/www/
    expose:
      - "80"
    command: ['nginx','-g','daemon off;']
  web3:
    image: nginx:1.14-alpine
    restart: always
    volumes:
      - ./web3/conf.d/:/etc/nginx/conf.d/
      - ./web3/logs/:/var/log/nginx/
      - ./www/:/www/
    expose:
      - "80"
    command: ['nginx','-g','daemon off;']
  web4:
    image: nginx:1.14-alpine
    restart: always
    volumes:
      - ./web4/conf.d/:/etc/nginx/conf.d/
      - ./web4/logs/:/var/log/nginx/
      - ./www/:/www/
    expose:
      - "80"
    command: ['nginx','-g','daemon off;']
  web5:
    image: nginx:1.14-alpine
    restart: always
    volumes:
      - ./web5/conf.d/:/etc/nginx/conf.d/
      - ./web5/logs/:/var/log/nginx/
      - ./www/:/www/
    expose:
      - "80"
    command: ['nginx','-g','daemon off;']
  php1:
    image: duanlujian/php:7.4.16-fpm-alpine-redis
    restart: always
    volumes:
      - ./www/:/www/
      - ./php/etc/:/usr/local/etc/php/
    expose:
      - "9000"
  php2:
    image: duanlujian/php:7.4.16-fpm-alpine-redis
    restart: always
    volumes:
      - ./www/:/www/
      - ./php/etc/:/usr/local/etc/php/
    expose:
      - "9000"
  php3:
    image: duanlujian/php:7.4.16-fpm-alpine-redis
    restart: always
    volumes:
      - ./www/:/www/
      - ./php/etc/:/usr/local/etc/php/
    expose:
      - "9000"
  php4:
    image: duanlujian/php:7.4.16-fpm-alpine-redis
    restart: always
    volumes:
      - ./www/:/www/
      - ./php/etc/:/usr/local/etc/php/
    expose:
      - "9000"
  php5:
    image: duanlujian/php:7.4.16-fpm-alpine-redis
    restart: always
    volumes:
      - ./www/:/www/
      - ./php/etc/:/usr/local/etc/php/
    expose:
      - "9000"
  db:
      image: "mysql:5.7.25"
      ports: 
        - "3306:3306"
      restart: always
      volumes:
        - ./mysql/data/:/var/lib/mysql/
        - ./mysql/conf.d/:/etc/mysql/conf.d/
        - ./mysql/tmp/:/tmp/
        - ./mysql/var/run/mysqld/:/var/run/mysqld/
      environment: 
        MYSQL_ROOT_PASSWORD: 111111
        MYSQL_USER: duanlujian
        MYSQL_PASSWORD: 111111
  redis:
      image: "redis:5.0.8-alpine"
      ports: 
        - "6379:6379"
      restart: always
      volumes:
        - ./redis/data/:/data/
        - ./redis/conf/:/usr/local/etc/redis/
      command: [
      "redis-server",
      "/usr/local/etc/redis/redis.conf",
      "--daemonize no",
      "--bind 0.0.0.0",
      "--appendonly yes",
      # "--save \"\"",
      "--aof-use-rdb-preamble yes"
      ]
      #configs:
      #- source: redis_conf
      #  target: /redis.conf
